# Generated by Django 4.2.5 on 2023-10-04 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integration", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="apiintegration",
            name="base_url",
            field=models.CharField(default="", max_length=256),
        ),
    ]
