# Generated by Django 4.2.5 on 2023-10-04 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integration", "0002_apiintegration_base_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlphavantageIntegration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("api_key", models.CharField(max_length=256)),
                ("base_url", models.CharField(default="", max_length=256)),
                ("user", models.CharField(max_length=256)),
                ("password", models.CharField(max_length=256)),
            ],
        ),
        migrations.DeleteModel(
            name="ApiIntegration",
        ),
    ]
