# Generated by Django 4.2.5 on 2023-10-04 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("integration", "0003_alphavantageintegration_delete_apiintegration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alphavantageintegration",
            name="password",
        ),
        migrations.RemoveField(
            model_name="alphavantageintegration",
            name="user",
        ),
    ]
