# Generated by Django 4.2.5 on 2023-10-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integration", "0004_remove_alphavantageintegration_password_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="YahooFinanceIntegration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("api_key", models.CharField(max_length=256)),
                ("api_host", models.CharField(max_length=256)),
                ("base_url", models.CharField(default="", max_length=256)),
            ],
        ),
    ]
