# Generated by Django 4.2.5 on 2023-10-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integration", "0005_yahoofinanceintegration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="yahoofinanceintegration",
            name="base_url",
            field=models.CharField(
                default="https://apidojo-yahoo-finance-v1.p.rapidapi.com/stock/v2",
                max_length=256,
            ),
        ),
    ]
