# Generated by Django 4.2.5 on 2023-10-09 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("integration", "0006_alter_yahoofinanceintegration_base_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="yahoofinanceintegration",
            name="base_url",
        ),
    ]
