# Generated by Django 4.2.5 on 2023-10-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_business_country_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuarterReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("earning", models.IntegerField()),
                ("revenue", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="YearlyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("earning", models.IntegerField()),
                ("revenue", models.IntegerField()),
            ],
        ),
    ]
