# Generated by Django 4.2.5 on 2023-10-09 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_quarterreport_yearlyreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="quarterreport",
            name="business",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.business",
            ),
        ),
        migrations.AddField(
            model_name="yearlyreport",
            name="business",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.business",
            ),
        ),
    ]
