# Generated by Django 4.2.5 on 2023-10-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_quarterreport_business_yearlyreport_business"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quarterreport",
            name="date",
        ),
        migrations.RemoveField(
            model_name="yearlyreport",
            name="date",
        ),
        migrations.AddField(
            model_name="quarterreport",
            name="quarter",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="quarterreport",
            name="year",
            field=models.IntegerField(default=1970),
        ),
        migrations.AddField(
            model_name="yearlyreport",
            name="year",
            field=models.IntegerField(default=1970),
        ),
    ]
