# Generated by Django 4.2.5 on 2023-10-10 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_quarterreport_date_remove_yearlyreport_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="business",
            options={"verbose_name": "Business", "verbose_name_plural": "Businesses"},
        ),
        migrations.AlterModelOptions(
            name="quarterreport",
            options={
                "verbose_name": "Quarter Report",
                "verbose_name_plural": "Quarter Reports",
            },
        ),
        migrations.AlterModelOptions(
            name="yearlyreport",
            options={
                "verbose_name": "Yearly Report",
                "verbose_name_plural": "Yearly Reports",
            },
        ),
        migrations.RenameField(
            model_name="business",
            old_name="Name",
            new_name="name",
        ),
        migrations.AddField(
            model_name="yearlyreport",
            name="capital_expenditure",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="yearlyreport",
            name="debt_repayment",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="yearlyreport",
            name="depreciation_and_ammortization",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="yearlyreport",
            name="end_cash_position",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="yearlyreport",
            name="free_cash_flow",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="yearlyreport",
            name="investing_cashflow",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="yearlyreport",
            name="net_income",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="yearlyreport",
            name="net_other_financing_charges",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="yearlyreport",
            name="operating_cash_flow",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="yearlyreport",
            name="other_non_cash_items",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="yearlyreport",
            name="purchase_of_investment",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="yearlyreport",
            name="sale_of_investment",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="yearlyreport",
            name="start_cash_position",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="yearlyreport",
            name="stock_based_compensation",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="yearlyreport",
            name="earning",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="yearlyreport",
            name="revenue",
            field=models.IntegerField(default=0),
        ),
    ]
