# Generated by Django 4.2.5 on 2023-10-12 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_quarterreport_earning_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="business",
            name="country_code",
            field=models.CharField(
                choices=[
                    ("FR", "France"),
                    ("DE", "Germany"),
                    ("ES", "Spain"),
                    ("CH", "Switzerland"),
                    ("UK", "United Kingdom"),
                    ("PT", "Portugal"),
                    ("BE", "Belgium"),
                    ("EL", "Greece"),
                    ("IE", "Ireland"),
                    ("LU", "Luxembourg"),
                    ("FI", "Finland"),
                    ("IT", "Italy"),
                    ("LI", "Liechtenstein"),
                    ("IS", "Iceland"),
                    ("NO", "Norway"),
                    ("SE", "Sweden"),
                    ("LT", "Lithuania"),
                    ("BG", "Bulgaria"),
                    ("CZ", "Czechia"),
                    ("HU", "Hungary"),
                    ("RO", "Romania"),
                    ("SI", "Slovenia"),
                    ("DK", "Denmark"),
                    ("HR", "Croatia"),
                    ("MT", "Malta"),
                    ("SK", "Slovakia"),
                    ("NL", "Netherlands"),
                    ("EE", "Estonia"),
                    ("CY", "Cyprus"),
                    ("AT", "Austria"),
                    ("LV", "Latvia"),
                    ("PL", "Poland"),
                ],
                default="FR",
                max_length=20,
            ),
        ),
    ]
