# Generated by Django 4.2.5 on 2023-10-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_business_last_update"),
    ]

    operations = [
        migrations.AlterField(
            model_name="business",
            name="last_update",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="quarterreport",
            name="earning",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="quarterreport",
            name="revenue",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="yearlyreport",
            name="capital_expenditure",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="yearlyreport",
            name="debt_repayment",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="yearlyreport",
            name="depreciation_and_ammortization",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="yearlyreport",
            name="earning",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="yearlyreport",
            name="end_cash_position",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="yearlyreport",
            name="free_cash_flow",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="yearlyreport",
            name="investing_cashflow",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="yearlyreport",
            name="net_income",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="yearlyreport",
            name="net_other_financing_charges",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="yearlyreport",
            name="operating_cash_flow",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="yearlyreport",
            name="other_non_cash_items",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="yearlyreport",
            name="purchase_of_investment",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="yearlyreport",
            name="revenue",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="yearlyreport",
            name="sale_of_investment",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="yearlyreport",
            name="start_cash_position",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="yearlyreport",
            name="stock_based_compensation",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
