# Generated by Django 4.2.5 on 2023-10-13 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_business_last_update_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DebugApiLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now=True)),
                ("url", models.CharField(max_length=256)),
                ("data", models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
