# Generated by Django 4.2.5 on 2023-10-13 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_debugapilog"),
    ]

    operations = [
        migrations.AddField(
            model_name="debugapilog",
            name="params",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
