# Generated by Django 4.2.5 on 2023-10-13 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_quarterreport_capital_expenditures_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_update", models.DateTimeField(blank=True, null=True)),
                (
                    "long_business_summary",
                    models.TextField(blank=True, default=None, null=True),
                ),
                ("website", models.CharField(blank=True, max_length=256, null=True)),
                ("country", models.CharField(blank=True, max_length=256, null=True)),
                ("city", models.CharField(blank=True, max_length=256, null=True)),
                ("fullTimeEmployees", models.IntegerField(blank=True, null=True)),
                ("marketCap", models.IntegerField(blank=True, null=True)),
                (
                    "business",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.business",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sector_key", models.CharField(blank=True, max_length=256, null=True)),
                ("sector", models.CharField(blank=True, max_length=256, null=True)),
                (
                    "sector_disp",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "business_info",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.businessinfo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Industry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "industry_key",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("industry", models.CharField(blank=True, max_length=256, null=True)),
                (
                    "business_info",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.businessinfo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AnalystGrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                ("firm", models.CharField(blank=True, max_length=256, null=True)),
                ("fromGrade", models.CharField(blank=True, max_length=256, null=True)),
                ("toGrade", models.CharField(blank=True, max_length=256, null=True)),
                ("action", models.CharField(blank=True, max_length=256, null=True)),
                (
                    "business_info",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.businessinfo",
                    ),
                ),
            ],
        ),
    ]
