# Generated by Django 4.2.5 on 2023-10-13 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_businessinfo_sector_industry_analystgrade"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="businessinfo",
            name="fullTimeEmployees",
        ),
        migrations.RemoveField(
            model_name="businessinfo",
            name="marketCap",
        ),
        migrations.RemoveField(
            model_name="industry",
            name="business_info",
        ),
        migrations.RemoveField(
            model_name="sector",
            name="business_info",
        ),
        migrations.AddField(
            model_name="businessinfo",
            name="full_time_employees",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="businessinfo",
            name="industry",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="core.industry",
            ),
        ),
        migrations.AddField(
            model_name="businessinfo",
            name="market_cap",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="businessinfo",
            name="sector",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="core.sector",
            ),
        ),
        migrations.AlterField(
            model_name="analystgrade",
            name="action",
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="analystgrade",
            name="business_info",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.businessinfo",
            ),
        ),
        migrations.AlterField(
            model_name="analystgrade",
            name="date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="analystgrade",
            name="firm",
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="analystgrade",
            name="fromGrade",
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="analystgrade",
            name="toGrade",
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="businessinfo",
            name="city",
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="businessinfo",
            name="country",
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="businessinfo",
            name="last_update",
            field=models.DateTimeField(auto_now=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="businessinfo",
            name="website",
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="industry",
            name="industry",
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="industry",
            name="industry_key",
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="sector",
            name="sector",
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="sector",
            name="sector_disp",
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="sector",
            name="sector_key",
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
    ]
