# Generated by Django 4.2.5 on 2023-10-13 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_remove_businessinfo_fulltimeemployees_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GradeFirm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, default=None, max_length=256, null=True
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="analystgrade",
            name="firm",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="core.gradefirm",
            ),
        ),
    ]
