# Generated by Django 4.2.5 on 2023-10-13 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_gradefirm_alter_analystgrade_firm"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True, default=None, null=True)),
                (
                    "open",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        default=None,
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "high",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        default=None,
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "low",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        default=None,
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "close",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        default=None,
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "adjclose",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        default=None,
                        max_digits=14,
                        null=True,
                    ),
                ),
                ("volume", models.IntegerField(blank=True, default=None, null=True)),
                (
                    "business",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.business",
                    ),
                ),
            ],
        ),
    ]
