# Generated by Django 4.2.5 on 2023-10-18 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_delete_debugapilog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businessinfo",
            name="business",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="business_info",
                to="core.business",
            ),
        ),
    ]
