# Generated by Django 4.2.5 on 2023-10-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_businessratio_years_of_cash_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businessratio",
            name="years_of_cash",
            field=models.DecimalField(
                blank=True, decimal_places=1, default=None, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="businessratio",
            name="years_to_repay_debt",
            field=models.DecimalField(
                blank=True, decimal_places=1, default=None, max_digits=10, null=True
            ),
        ),
    ]
